spring:
  application:
    name: aws-s3-notify
  server:
    port: 80
input:
  bucket:
    region: us-west-1
    name: cjf-epsilon-demos
    keyPrefix: installers
  filter:
    - SEARCHFORCE_STARTED_PROCESSING
