spring:
  application:
    name: aws-s3-notify
  server:
    port: 80
input:
  bucket:
    region: us-west-1
    name: cjf-epsilon-demos
    keyPrefix: installers
  skipFolders: true
  tagFilter:
    minus:
      - SEARCHFORCE_STARTED_PROCESSING
transform:
  local:
    dir: /tmp
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
